/**
 * English translations for common section
 * Generated by i18n-migration manual process
 * @generated 2025-09-02
 */

const commonTranslations = {
  loading: 'Loading...',
  error: 'Error',
  success: 'Success',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  edit: 'Edit',
  create: 'Create',
  search: 'Search',
  filter: 'Filter',
  back: 'Back',
  next: 'Next',
  previous: 'Previous',
  confirm: 'Confirm',
  logout: 'Logout',
  tomorrow: 'Tomorrow',
  refresh: 'Refresh',
  notifications: {
    actions: {
      closeNotification: 'Close notification',
    },
  },
};

export default commonTranslations;