/**
 * Español translations for common section
 * Generated by i18n-migration manual process
 * @generated 2025-09-02
 */

const commonTranslations = {
  loading: 'Cargando...',
  error: 'Error',
  success: 'Éxito',
  save: 'Guardar',
  cancel: 'Cancelar',
  delete: 'Eliminar',
  edit: 'Editar',
  create: 'Crear',
  search: 'Buscar',
  filter: 'Filtrar',
  back: 'Atrás',
  next: 'Siguiente',
  previous: 'Anterior',
  confirm: 'Confirmar',
  logout: 'Cerrar sesión',
  tomorrow: 'Mañana',
  refresh: 'Actualizar',
};

export default commonTranslations;