/**
 * Italiano translations for common section
 * Generated by i18n-migration manual process
 * @generated 2025-09-02
 */

const commonTranslations = {
  loading: 'Caricamento...',
  error: 'Errore',
  success: 'Successo',
  save: 'Salva',
  cancel: 'Annulla',
  delete: 'Elimina',
  edit: 'Modifica',
  create: 'Crea',
  search: 'Cerca',
  filter: 'Filtra',
  back: 'Indietro',
  next: 'Avanti',
  previous: 'Precedente',
  confirm: 'Conferma',
  logout: 'Esci',
  tomorrow: 'Domani',
  refresh: 'Aggiorna',
  notifications: {
    actions: {
      closeNotification: 'Chiudi notifica',
    },
  },
};

export default commonTranslations;