/**
 * English translations for dashboard section
 * Generated by i18n-migration process
 * @generated 2025-09-02
 */

const dashboardTranslations = {
  welcome: {
    title: 'Welcome, {{name}}',
    subtitle: 'Manage your holidays and view team calendar',
  },
  navigation: {
    dashboard: 'Dashboard',
    overview: 'Overview',
    overviewDesc: 'General overview',
    calendar: 'Calendar',
    requests: 'My Requests',
    profile: 'Profile',
    logout: 'Logout',
  },
  profile: {
    title: 'Employee Profile',
    editButton: 'Edit Profile',
    status: {
      active: 'Active',
      pending: 'Pending',
      inactive: 'Inactive',
    },
    role: {
      admin: 'Administrator',
      employee: 'Employee',
    },
    fields: {
      department: 'Not assigned',
      phone: 'Not provided',
      jobTitle: 'Not specified',
    },
  },
  stats: {
    availableDays: 'Available days',
    usedDays: 'Used days',
    pendingRequests: 'Pending requests',
    upcomingHolidays: 'Upcoming holidays',
    completedHolidays: 'Completed Holidays',
    requestsOverview: 'Requests Overview',
    totalRequests: 'Total Requests',
    totalRequestsDesc: 'Requests created this year',
    approvedRequests: 'Approved Requests',
    approvedRequestsDesc: 'Approvals received',
    rejectedRequests: 'Rejected',
    rejectedRequestsDesc: 'Rejected requests',
  },
  calendar: {
    monthView: 'Month view',
    weekView: 'Week view',
    dayView: 'List',
    listView: 'Events list',
    today: 'Today',
    myHolidays: 'My holidays',
    teamHolidays: 'Team holidays',
    allHolidays: 'All',
    newRequest: 'New request',
    legend: 'Legend',
    teamMembers: 'Team Members',
    members: 'members',
    employees: 'employees',
    noEmployeesFound: 'No employees found',
    noHolidaysFound: 'No holidays found',
    requestCreationError: 'Error creating request',
    addHoliday: 'Add Request',
    dialogs: {
      holidayDetails: {
        title: 'Holiday Details',
        description: 'Complete information about the selected holiday request'
      },
      dayEvents: {
        title: 'Holidays on',
        description: 'Complete list of all employees on holiday on this date'
      }
    },
    views: {
      timeline: 'Timeline',
      monthly: 'Month',
      weekly: 'Week',
      list: 'List',
    },
    viewModes: {
      own: 'My',
      team: 'Team',
      all: 'All',
    },
    dateFilters: {
      label: 'Filter by period',
      all: 'All dates',
      yearToDate: 'Year to date',
      last12Months: 'Last 12 months',
      last6Months: 'Last 6 months',
      last3Months: 'Last 3 months',
      next3Months: 'Next 3 months',
      next6Months: 'Next 6 months',
      next12Months: 'Next 12 months',
    },
    legendDetails: {
      approved: 'Approved',
      pending: 'Pending',
      rejected: 'Rejected',
      vacation: 'Vacation',
      sick: 'Sick leave',
      personal: 'Personal day',
    },
    bigCalendar: {
      allDay: 'All day',
      previous: 'Previous',
      next: 'Next',
      today: 'Today',
      month: 'Month',
      week: 'Week',
      day: 'Day',
      agenda: 'Timeline',
      date: 'Date',
      time: 'Time',
      event: 'Event',
      noEventsInRange: 'No holidays in this period',
    },
  },
  holidays: {
    title: 'My requests',
    status: 'Status',
    statusDetails: {
      approved: 'Approved',
      pending: 'Pending approval',
      pendingShort: 'Pending',
      rejected: 'Rejected',
    },
    dates: 'Dates',
    type: 'Type',
    notes: 'Notes',
    actions: 'Actions',
    noRequests: 'No holiday requests',
    cancelRequest: 'Cancel request',
    editRequest: 'Edit request',
    downloadError: 'Error downloading certificate',
    request: {
      title: 'New Holiday Request',
    },
  },
};

export default dashboardTranslations;