/**
 * Español translations for dashboard section
 * Generated by i18n-migration process
 * @generated 2025-09-02
 */

const dashboardTranslations = {
  welcome: {
    title: 'Bienvenido, {{name}}',
    subtitle: 'Gestiona tus vacaciones y visualiza el calendario del equipo',
  },
  navigation: {
    dashboard: 'Dashboard',
    overview: 'Vista general',
    overviewDesc: 'Resumen general',
    calendar: 'Calendario',
    requests: 'Mis Solicitudes',
    profile: 'Perfil',
    logout: 'Cerrar sesión',
  },
  profile: {
    title: 'Perfil del Empleado',
    editButton: 'Editar Perfil',
    status: {
      active: 'Activo',
      pending: 'Pendiente',
      inactive: 'Inactivo',
    },
    role: {
      admin: 'Administrador',
      employee: 'Empleado',
    },
    fields: {
      department: 'No asignado',
      phone: 'No proporcionado',
      jobTitle: 'No especificado',
    },
  },
  stats: {
    availableDays: 'Días disponibles',
    usedDays: 'Días utilizados',
    pendingRequests: 'Solicitudes pendientes',
    upcomingHolidays: 'Próximas vacaciones',
    completedHolidays: 'Vacaciones Disfrutadas',
    requestsOverview: 'Resumen de Solicitudes',
    totalRequests: 'Solicitudes Totales',
    totalRequestsDesc: 'Solicitudes creadas este año',
    approvedRequests: 'Solicitudes Aprobadas',
    approvedRequestsDesc: 'Aprobaciones recibidas',
    rejectedRequests: 'Rechazadas',
    rejectedRequestsDesc: 'Solicitudes rechazadas',
  },
  calendar: {
    monthView: 'Vista mensual',
    weekView: 'Vista semanal',
    dayView: 'Lista',
    listView: 'Lista de eventos',
    today: 'Hoy',
    myHolidays: 'Mis vacaciones',
    teamHolidays: 'Vacaciones del equipo',
    allHolidays: 'Todas',
    newRequest: 'Nueva solicitud',
    legend: 'Leyenda',
    teamMembers: 'Miembros del Equipo',
    members: 'miembros',
    employees: 'empleados',
    noEmployeesFound: 'No se encontraron empleados',
    noHolidaysFound: 'No se encontraron vacaciones',
    requestCreationError: 'Error al crear la solicitud',
    addHoliday: 'Añadir Solicitud',
    dialogs: {
      holidayDetails: {
        title: 'Detalles de Vacaciones',
        description: 'Información completa sobre la solicitud de vacaciones seleccionada'
      },
      dayEvents: {
        title: 'Vacaciones del',
        description: 'Lista completa de todos los empleados de vacaciones en esta fecha'
      }
    },
    views: {
      timeline: 'Timeline',
      monthly: 'Mes',
      weekly: 'Semana',
      list: 'Lista',
    },
    viewModes: {
      own: 'Mis',
      team: 'Equipo',
      all: 'Todas',
    },
    dateFilters: {
      label: 'Filtrar por período',
      all: 'Todas las fechas',
      yearToDate: 'Desde inicio del año hasta hoy',
      last12Months: 'Últimos 12 meses',
      last6Months: 'Últimos 6 meses',
      last3Months: 'Últimos 3 meses',
      next3Months: 'Próximos 3 meses',
      next6Months: 'Próximos 6 meses',
      next12Months: 'Próximos 12 meses',
    },
    legendDetails: {
      approved: 'Aprobada',
      pending: 'Pendiente',
      rejected: 'Rechazada',
      vacation: 'Vacaciones',
      sick: 'Baja médica',
      personal: 'Día personal',
    },
    bigCalendar: {
      allDay: 'Todo el día',
      previous: 'Anterior',
      next: 'Siguiente',
      today: 'Hoy',
      month: 'Mes',
      week: 'Semana',
      day: 'Día',
      agenda: 'Timeline',
      date: 'Fecha',
      time: 'Hora',
      event: 'Evento',
      noEventsInRange: 'No hay vacaciones en este período',
    },
  },
  holidays: {
    title: 'Mis solicitudes',
    status: 'Estado',
    statusDetails: {
      approved: 'Aprobada',
      pending: 'Pendiente de aprobación',
      pendingShort: 'Pendiente',
      rejected: 'Rechazada',
    },
    dates: 'Fechas',
    type: 'Tipo',
    notes: 'Notas',
    actions: 'Acciones',
    noRequests: 'Sin solicitudes de vacaciones',
    cancelRequest: 'Cancelar solicitud',
    editRequest: 'Editar solicitud',
    downloadError: 'Error al descargar el certificado',
    request: {
      title: 'Nueva Solicitud de Vacaciones',
    },
  },
};

export default dashboardTranslations;