/**
 * Italiano translations for dashboard section
 * Generated by i18n-migration process
 * @generated 2025-09-02
 */

const dashboardTranslations = {
  welcome: {
    title: 'Benvenuto, {{name}}',
    subtitle: 'Gestisci le tue ferie e visualizza il calendario del team',
  },
  navigation: {
    dashboard: 'Dashboard',
    overview: 'Panoramica',
    overviewDesc: 'Panoramica generale',
    calendar: 'Calendario',
    requests: 'Le Mie Richieste',
    profile: 'Profilo',
    logout: 'Esci',
  },
  profile: {
    title: 'Profilo Dipendente',
    editButton: 'Modifica Profilo',
    status: {
      active: 'Attivo',
      pending: 'In attesa',
      inactive: 'Inattivo',
    },
    role: {
      admin: 'Amministratore',
      employee: 'Dipendente',
    },
    fields: {
      department: 'Non assegnato',
      phone: 'Non inserito',
      jobTitle: 'Non specificata',
    },
  },
  stats: {
    availableDays: 'Giorni disponibili',
    usedDays: 'Giorni utilizzati',
    pendingRequests: 'Richieste in attesa',
    upcomingHolidays: 'Prossime ferie',
    completedHolidays: 'Ferie Godute',
    requestsOverview: 'Panoramica Richieste',
    totalRequests: 'Richieste Totali',
    totalRequestsDesc: 'Richieste create quest\'anno',
    approvedRequests: 'Richieste Approvate',
    approvedRequestsDesc: 'Approvazioni ricevute',
    rejectedRequests: 'Rifiutate',
    rejectedRequestsDesc: 'Richieste rifiutate',
  },
  calendar: {
    monthView: 'Vista mensile',
    weekView: 'Vista settimanale',
    dayView: 'Lista',
    listView: 'Lista eventi',
    today: 'Oggi',
    myHolidays: 'Le mie ferie',
    teamHolidays: 'Ferie del team',
    allHolidays: 'Tutti',
    newRequest: 'Nuova richiesta',
    legend: 'Legenda',
    teamMembers: 'Membri del Team',
    members: 'membri',
    employees: 'dipendenti',
    noEmployeesFound: 'Nessun dipendente trovato',
    noHolidaysFound: 'Nessuna ferie trovata',
    requestCreationError: 'Errore durante la creazione della richiesta',
    addHoliday: 'Nuova Richiesta',
    dialogs: {
      holidayDetails: {
        title: 'Dettagli Ferie',
        description: 'Informazioni complete sulla richiesta di ferie selezionata'
      },
      dayEvents: {
        title: 'Ferie del',
        description: 'Elenco completo di tutti i dipendenti in ferie in questa data'
      }
    },
    views: {
      timeline: 'Timeline',
      monthly: 'Mese',
      weekly: 'Sett.',
      list: 'Lista',
    },
    viewModes: {
      own: 'Proprie',
      team: 'Team',
      all: 'Tutti',
    },
    dateFilters: {
      label: 'Filtra per periodo',
      all: 'Tutte le date',
      yearToDate: 'Da inizio anno ad oggi',
      last12Months: 'Ultimi 12 mesi',
      last6Months: 'Ultimi 6 mesi',
      last3Months: 'Ultimi 3 mesi',
      next3Months: 'Prossimi 3 mesi',
      next6Months: 'Prossimi 6 mesi',
      next12Months: 'Prossimi 12 mesi',
    },
    legendDetails: {
      approved: 'Approvata',
      pending: 'In attesa',
      rejected: 'Rifiutata',
      vacation: 'Ferie',
      sick: 'Malattia',
      personal: 'Permesso personale',
    },
    bigCalendar: {
      allDay: 'Tutto il giorno',
      previous: 'Precedente',
      next: 'Successivo',
      today: 'Oggi',
      month: 'Mese',
      week: 'Settimana',
      day: 'Giorno',
      agenda: 'Timeline',
      date: 'Data',
      time: 'Ora',
      event: 'Evento',
      noEventsInRange: 'Nessun permesso in questo periodo',
    },
  },
  holidays: {
    title: 'Le mie richieste',
    status: 'Stato',
    statusDetails: {
      approved: 'Approvata',
      pending: 'In attesa di approvazione',
      pendingShort: 'In attesa',
      rejected: 'Rifiutata',
    },
    dates: 'Date',
    type: 'Tipo',
    notes: 'Note',
    actions: 'Azioni',
    noRequests: 'Nessuna richiesta di ferie',
    cancelRequest: 'Annulla richiesta',
    editRequest: 'Modifica richiesta',
    downloadError: 'Errore durante il download del certificato',
    request: {
      title: 'Nuova Richiesta Ferie',
    },
  },
};

export default dashboardTranslations;