/**
 * English translations for auth section
 * Generated by i18n-migration manual process
 * @generated 2025-09-02
 */

const authTranslations = {
  login: {
    title: 'Sign In',
    subtitle: '{{companyName}} Holiday Management System',
    email: 'Email',
    password: 'Password',
    submit: 'Sign In',
    forgotPassword: 'Forgot password?',
    noAccount: "Don't have an account?",
    register: 'Register',
    invalidCredentials: 'Invalid email or password',
    accountPending: 'Your account is pending approval',
  },
  register: {
    title: 'Register',
    subtitle: 'Create your {{companyName}} account',
    name: 'Full name',
    email: 'Company email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    submit: 'Register',
    hasAccount: 'Already have an account?',
    login: 'Sign In',
    emailDomain: 'Use your @ominiaservice.net email',
    passwordMismatch: 'Passwords do not match',
    registrationSuccess: 'Registration complete! Wait for admin approval',
  },
};

export default authTranslations;