/**
 * Español translations for auth section
 * Generated by i18n-migration manual process
 * @generated 2025-09-02
 */

const authTranslations = {
  login: {
    title: 'Iniciar sesión',
    subtitle: 'Sistema de gestión de vacaciones {{companyName}}',
    email: 'Correo electrónico',
    password: 'Contraseña',
    submit: 'Iniciar sesión',
    forgotPassword: '¿Olvidaste tu contraseña?',
    noAccount: '¿No tienes una cuenta?',
    register: 'Registrarse',
    invalidCredentials: 'Correo o contraseña inválidos',
    accountPending: 'Tu cuenta está pendiente de aprobación',
  },
  register: {
    title: 'Registro',
    subtitle: 'Crea tu cuenta {{companyName}}',
    name: 'Nombre completo',
    email: 'Correo corporativo',
    password: 'Contraseña',
    confirmPassword: 'Confirmar contraseña',
    submit: 'Registrarse',
    hasAccount: '¿Ya tienes una cuenta?',
    login: 'Iniciar sesión',
    emailDomain: 'Usa tu correo @ominiaservice.net',
    passwordMismatch: 'Las contraseñas no coinciden',
    registrationSuccess: '¡Registro completado! Espera la aprobación del administrador',
  },
};

export default authTranslations;