/**
 * Italiano translations for auth section
 * Generated by i18n-migration manual process
 * @generated 2025-09-02
 */

const authTranslations = {
  login: {
    title: 'Accedi',
    subtitle: 'Sistema di gestione ferie {{companyName}}',
    email: 'Email',
    password: 'Password',
    submit: 'Accedi',
    forgotPassword: 'Password dimenticata?',
    noAccount: 'Non hai un account?',
    register: 'Registrati',
    invalidCredentials: 'Email o password non validi',
    accountPending: 'Il tuo account è in attesa di approvazione',
  },
  register: {
    title: 'Registrazione',
    subtitle: 'Crea il tuo account {{companyName}}',
    name: 'Nome completo',
    email: 'Email aziendale',
    password: 'Password',
    confirmPassword: 'Conferma password',
    submit: 'Registrati',
    hasAccount: 'Hai già un account?',
    login: 'Accedi',
    emailDomain: 'Usa la tua email @ominiaservice.net',
    passwordMismatch: 'Le password non corrispondono',
    registrationSuccess: 'Registrazione completata! Attendi l\'approvazione dell\'amministratore',
  },
};

export default authTranslations;